name: meson
version: '0.43.0'
summary: The Meson Build System
description: |
  Meson® is a project to create the best possible next-generation build system.

confinement: classic

apps:
  meson:
    command: meson

parts:
  meson:
    source: https://github.com/mesonbuild/meson.git
    source-tag: '0.43.0'
    plugin: python
